### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by femans** [ipfs-search/ipfs-search-queue-pinservice#1]
- [x] improved readme for testing/running
- [x] docker script
- [x] cluster server file fixed
- [x] All ENV vars for HOST, PORT and QUEUE_HOST implemented
- [x] complete input validation
- [x] error handling
